# Generated by Django 6.0.5 on 2026-05-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('status', models.CharField(choices=[('nao_iniciado', 'Não iniciado'), ('aprovado', 'Aprovado'), ('paralisado', 'Paralisado'), ('finalizado', 'Finalizado')], default='nao_iniciado', max_length=20)),
            ],
        ),
    ]
